import { getSiteType } from "./site-data";
import { Cargo } from "./types";

export const getAverageHauls = (type: string): number => {
  const total = Object.values(getAvgHaulCosts(type)).reduce((sum, val) => sum += val, 0);
  return total;
}

export const getAvgHaulCosts = (type: string): Cargo => {
  type = type.replace('?', '');
  switch (type) {
    case '':
    case ' (primary)':
      return {};

    case 'plutus':
    case 'vulcan':
    case 'dysnomia':
    case 'vesta':
    case 'prometheus':
    case 'nemesis':
    case 'Commercial Outpost':
    case 'Industrial Outpost':
    case 'Pirate Outpost':
    case 'Civilian Outpost':
    case 'Scientific Outpost':
    case 'Military Outpost':
      return avgHaulCosts['orbital-outpost'];

    case 'plutus (primary)':
    case 'vulcan (primary)':
    case 'dysnomia (primary)':
    case 'vesta (primary)':
    case 'prometheus (primary)':
    case 'nemesis (primary)':
    case 'Commercial Outpost (primary)':
    case 'Industrial Outpost (primary)':
    case 'Pirate Outpost (primary)':
    case 'Civilian Outpost (primary)':
    case 'Scientific Outpost (primary)':
    case 'Military Outpost (primary)':
      return avgHaulCosts['orbital-outpost-primary'];

    case 'no_truss':
    case 'dual_truss':
    case 'quad_truss':
    case 'Coriolis Starport':
      return avgHaulCosts['coriolis'];

    case 'no_truss (primary)':
    case 'dual_truss (primary)':
    case 'quad_truss (primary)':
    case 'Coriolis Starport (primary)':
      return avgHaulCosts['coriolis-primary'];

    case 'asteroid':
    case 'Asteroid Starport':
      return avgHaulCosts['asteroid'];

    case 'asteroid (primary)':
    case 'Asteroid Starport (primary)':
      return avgHaulCosts['asteroid-primary'];

    case 'ocellus':
    case 'Ocellus Starport':
      return avgHaulCosts['ocellus'];

    case 'ocellus (primary)':
    case 'Ocellus Starport (primary)':
      return avgHaulCosts['ocellus-primary'];


    case 'apollo':
    case 'artemis':
    case 'Orbis Starport':
      return avgHaulCosts['orbis'];

    case 'apollo (primary)':
    case 'artemis (primary)':
    case 'Orbis Starport (primary)':
      return avgHaulCosts['orbis-primary'];

    case 'dodec':
    case 'quint_truss':
    case 'dec_truss':
    case 'Dodec Starport':
      return avgHaulCosts['dodec'];

    case 'dodec (primary)':
    case 'quint_truss (primary)':
    case 'dec_truss (primary)':
    case 'Dodec Starport (primary)':
      return avgHaulCosts['dodec-primary'];

    case "Industrial Surface Outpost":
    case "bia":
    case "hephaestus":
    case "mefitis":
    case "opis":
    case "ponos":
    case "tethys":
    case "Scientific Surface Outpost":
    case "ananke":
    case "antevorta":
    case "fauna":
    case "necessitas":
    case "porrima":
    case "providentia":
    case "Civilian Surface Outpost":
    case "atropos":
    case "clotho":
    case "decima":
    case "hestia":
    case "lachesis":
    case "nona":
      return avgHaulCosts['surface-outpost'];
  }

  let costs = avgHaulCosts[type];
  if (!costs) {
    const groupType = getSiteType(type)!;
    costs = avgHaulCosts[groupType.displayName2];
  }

  if (!costs) {
    throw new Error(`No costs for: ${type}`);
  }
  return costs;
}

const avgHaulCosts: Record<string, Cargo> = {
  'orbital-outpost': {
    "ceramiccomposites": 497,
    "cmmcomposite": 3912,
    "computercomponents": 50,
    "copper": 218,
    "foodcartridges": 94,
    "fruitandvegetables": 50,
    "insulatingmembrane": 311,
    "liquidoxygen": 1553,
    "medicaldiagnosticequipment": 13,
    "nonlethalweapons": 13,
    "polymers": 497,
    "powergenerators": 19,
    "semiconductors": 56,
    "steel": 5588,
    "superconductors": 100,
    "titanium": 4843,
    "water": 621,
    "waterpurifiers": 38
  },
  'orbital-outpost-primary': {
    "aluminium": 500,
    "ceramiccomposites": 521,
    "cmmcomposite": 4508,
    "computercomponents": 62,
    "copper": 242,
    "foodcartridges": 94,
    "fruitandvegetables": 50,
    "insulatingmembrane": 347,
    "liquidoxygen": 1792,
    "medicaldiagnosticequipment": 13,
    "nonlethalweapons": 13,
    "polymers": 521,
    "powergenerators": 19,
    "semiconductors": 68,
    "steel": 6660,
    "superconductors": 112,
    "titanium": 5534,
    "water": 741,
    "waterpurifiers": 38
  },
  'coriolis': {
    "aluminium": 10055,
    "ceramiccomposites": 1207,
    "cmmcomposite": 11261,
    "computercomponents": 145,
    "copper": 644,
    "foodcartridges": 242,
    "fruitandvegetables": 145,
    "insulatingmembrane": 644,
    "liquidoxygen": 3781,
    "medicaldiagnosticequipment": 25,
    "nonlethalweapons": 25,
    "polymers": 1046,
    "powergenerators": 65,
    "semiconductors": 161,
    "steel": 14076,
    "superconductors": 282,
    "titanium": 8205,
    "water": 1609,
    "waterpurifiers": 105
  },
  'coriolis-primary': {
    "aluminium": 12555,
    "ceramiccomposites": 1327,
    "cmmcomposite": 14241,
    "computercomponents": 205,
    "copper": 764,
    "foodcartridges": 242,
    "fruitandvegetables": 145,
    "insulatingmembrane": 824,
    "liquidoxygen": 4976,
    "medicaldiagnosticequipment": 25,
    "nonlethalweapons": 25,
    "polymers": 1166,
    "powergenerators": 65,
    "semiconductors": 221,
    "steel": 19436,
    "superconductors": 342,
    "titanium": 11660,
    "water": 2209,
    "waterpurifiers": 105
  },
  'asteroid': {
    "aluminium": 10055,
    "ceramiccomposites": 1207,
    "cmmcomposite": 11261,
    "computercomponents": 145,
    "copper": 644,
    "foodcartridges": 242,
    "fruitandvegetables": 145,
    "insulatingmembrane": 644,
    "liquidoxygen": 3781,
    "medicaldiagnosticequipment": 25,
    "nonlethalweapons": 25,
    "polymers": 1046,
    "powergenerators": 65,
    "semiconductors": 161,
    "steel": 14076,
    "superconductors": 282,
    "titanium": 8205,
    "water": 1609,
    "waterpurifiers": 105
  },
  'asteroid-primary': {
    "aluminium": 12555,
    "ceramiccomposites": 1327,
    "cmmcomposite": 14241,
    "computercomponents": 205,
    "copper": 764,
    "foodcartridges": 242,
    "fruitandvegetables": 145,
    "insulatingmembrane": 824,
    "liquidoxygen": 4976,
    "medicaldiagnosticequipment": 25,
    "nonlethalweapons": 25,
    "polymers": 1166,
    "powergenerators": 65,
    "semiconductors": 221,
    "steel": 19436,
    "superconductors": 342,
    "titanium": 11660,
    "water": 2209,
    "waterpurifiers": 105
  },
  'ocellus': {
    "aluminium": 40220,
    "ceramiccomposites": 4828,
    "cmmcomposite": 45044,
    "computercomponents": 290,
    "copper": 2576,
    "foodcartridges": 484,
    "fruitandvegetables": 290,
    "insulatingmembrane": 1288,
    "liquidoxygen": 15124,
    "medicaldiagnosticequipment": 50,
    "nonlethalweapons": 50,
    "polymers": 2092,
    "powergenerators": 130,
    "semiconductors": 322,
    "steel": 56304,
    "superconductors": 564,
    "titanium": 32820,
    "water": 6436,
    "waterpurifiers": 210
  },
  'ocellus-primary': {
    "aluminium": 45220,
    "ceramiccomposites": 5068,
    "cmmcomposite": 51004,
    "computercomponents": 410,
    "copper": 2816,
    "foodcartridges": 484,
    "fruitandvegetables": 290,
    "insulatingmembrane": 1648,
    "liquidoxygen": 17514,
    "medicaldiagnosticequipment": 50,
    "nonlethalweapons": 50,
    "polymers": 2332,
    "powergenerators": 130,
    "semiconductors": 442,
    "steel": 67024,
    "superconductors": 684,
    "titanium": 39730,
    "water": 7636,
    "waterpurifiers": 210
  },
  'orbis': {
    "aluminium": 40220,
    "ceramiccomposites": 4828,
    "cmmcomposite": 45044,
    "computercomponents": 290,
    "copper": 2576,
    "foodcartridges": 484,
    "fruitandvegetables": 290,
    "insulatingmembrane": 1288,
    "liquidoxygen": 15124,
    "medicaldiagnosticequipment": 50,
    "nonlethalweapons": 50,
    "polymers": 2092,
    "powergenerators": 130,
    "semiconductors": 322,
    "steel": 56304,
    "superconductors": 564,
    "titanium": 32820,
    "water": 6436,
    "waterpurifiers": 210
  },
  'orbis-primary': {
    "aluminium": 45220,
    "ceramiccomposites": 5068,
    "cmmcomposite": 51004,
    "computercomponents": 410,
    "copper": 2816,
    "foodcartridges": 484,
    "fruitandvegetables": 290,
    "insulatingmembrane": 1648,
    "liquidoxygen": 17514,
    "medicaldiagnosticequipment": 50,
    "nonlethalweapons": 50,
    "polymers": 2332,
    "powergenerators": 130,
    "semiconductors": 442,
    "steel": 67024,
    "superconductors": 684,
    "titanium": 39730,
    "water": 7636,
    "waterpurifiers": 210
  },
  'dodec': {
    "aluminium": 45248,
    "autofabricators": 314,
    "ceramiccomposites": 5432,
    "cmmcomposite": 50675,
    "computercomponents": 363,
    "copper": 2898,
    "foodcartridges": 605,
    "fruitandvegetables": 363,
    "insulatingmembrane": 1610,
    "liquidoxygen": 17015,
    "medicaldiagnosticequipment": 63,
    "nonlethalweapons": 63,
    "polymers": 2615,
    "powergenerators": 163,
    "semiconductors": 403,
    "steel": 63342,
    "superconductors": 705,
    "titanium": 36923,
    "water": 7241,
    "waterpurifiers": 263
  },
  'dodec-primary': {
    "aluminium": 50248,
    "autofabricators": 314,
    "ceramiccomposites": 5672,
    "cmmcomposite": 56635,
    "computercomponents": 483,
    "copper": 3138,
    "foodcartridges": 605,
    "fruitandvegetables": 363,
    "insulatingmembrane": 1970,
    "liquidoxygen": 19405,
    "medicaldiagnosticequipment": 63,
    "nonlethalweapons": 63,
    "polymers": 2855,
    "powergenerators": 163,
    "semiconductors": 523,
    "steel": 74062,
    "superconductors": 825,
    "titanium": 43833,
    "water": 8441,
    "waterpurifiers": 263
  },

  'surface-outpost': {
    "aluminium": 7047,
    "buildingfabricators": 407,
    "ceramiccomposites": 814,
    "cmmcomposite": 6776,
    "computercomponents": 102,
    "copper": 407,
    "emergencypowercells": 68,
    "evacuationshelter": 204,
    "foodcartridges": 136,
    "fruitandvegetables": 95,
    "liquidoxygen": 2372,
    "medicaldiagnosticequipment": 48,
    "nonlethalweapons": 34,
    "polymers": 678,
    "powergenerators": 68,
    "semiconductors": 102,
    "steel": 10164,
    "structuralregulators": 678,
    "superconductors": 136,
    "surfacestabilisers": 610,
    "survivalequipment": 55,
    "terrainenrichmentsystems": 68,
    "titanium": 5760
  },
  "Agriculture Settlement: Large": {
    "aluminium": 1677,
    "biowaste": 840,
    "buildingfabricators": 126,
    "ceramiccomposites": 84,
    "computercomponents": 42,
    "copper": 63,
    "cropharvesters": 630,
    "emergencypowercells": 252,
    "evacuationshelter": 42,
    "foodcartridges": 126,
    "fruitandvegetables": 189,
    "grain": 231,
    "liquidoxygen": 672,
    "pesticides": 378,
    "polymers": 273,
    "steel": 2304,
    "structuralregulators": 168,
    "surfacestabilisers": 168,
    "survivalequipment": 42,
    "terrainenrichmentsystems": 210
  },
  "Agriculture Settlement: Medium": {
    "aluminium": 1118,
    "biowaste": 560,
    "buildingfabricators": 84,
    "ceramiccomposites": 56,
    "computercomponents": 28,
    "copper": 42,
    "cropharvesters": 420,
    "emergencypowercells": 168,
    "evacuationshelter": 28,
    "foodcartridges": 84,
    "fruitandvegetables": 126,
    "grain": 154,
    "liquidoxygen": 448,
    "pesticides": 252,
    "polymers": 182,
    "steel": 1536,
    "structuralregulators": 112,
    "surfacestabilisers": 112,
    "survivalequipment": 28,
    "terrainenrichmentsystems": 140
  },
  "Agriculture Settlement: Small": {
    "aluminium": 559,
    "biowaste": 280,
    "buildingfabricators": 42,
    "ceramiccomposites": 28,
    "computercomponents": 14,
    "copper": 21,
    "cropharvesters": 210,
    "emergencypowercells": 84,
    "evacuationshelter": 14,
    "foodcartridges": 42,
    "fruitandvegetables": 63,
    "grain": 77,
    "liquidoxygen": 224,
    "pesticides": 126,
    "polymers": 91,
    "steel": 768,
    "structuralregulators": 56,
    "surfacestabilisers": 56,
    "survivalequipment": 14,
    "terrainenrichmentsystems": 70
  },
  "Bio Settlement: Large": {
    "advancedcatalysers": 285,
    "aluminium": 1821,
    "basicmedicines": 42,
    "buildingfabricators": 162,
    "ceramiccomposites": 123,
    "computercomponents": 123,
    "copper": 102,
    "emergencypowercells": 81,
    "evacuationshelter": 81,
    "foodcartridges": 123,
    "fruitandvegetables": 81,
    "geologicalequipment": 81,
    "hazardousenvironmentsuits": 81,
    "liquidoxygen": 1053,
    "medicaldiagnosticequipment": 123,
    "microcontrollers": 42,
    "mutomimager": 285,
    "polymers": 345,
    "semiconductors": 63,
    "steel": 2835,
    "structuralregulators": 243,
    "superconductors": 63,
    "surfacestabilisers": 243,
    "survivalequipment": 42
  },
  "Bio Settlement: Medium": {
    "advancedcatalysers": 190,
    "aluminium": 1214,
    "basicmedicines": 28,
    "buildingfabricators": 108,
    "ceramiccomposites": 82,
    "computercomponents": 82,
    "copper": 68,
    "emergencypowercells": 54,
    "evacuationshelter": 54,
    "foodcartridges": 82,
    "fruitandvegetables": 54,
    "geologicalequipment": 54,
    "hazardousenvironmentsuits": 54,
    "liquidoxygen": 702,
    "medicaldiagnosticequipment": 82,
    "microcontrollers": 28,
    "mutomimager": 190,
    "polymers": 230,
    "semiconductors": 42,
    "steel": 1890,
    "structuralregulators": 162,
    "superconductors": 42,
    "surfacestabilisers": 162,
    "survivalequipment": 28
  },
  "Bio Settlement: Small": {
    "advancedcatalysers": 95,
    "aluminium": 607,
    "basicmedicines": 14,
    "buildingfabricators": 54,
    "ceramiccomposites": 41,
    "computercomponents": 41,
    "copper": 34,
    "emergencypowercells": 27,
    "evacuationshelter": 27,
    "foodcartridges": 41,
    "fruitandvegetables": 27,
    "geologicalequipment": 27,
    "hazardousenvironmentsuits": 27,
    "liquidoxygen": 351,
    "medicaldiagnosticequipment": 41,
    "microcontrollers": 14,
    "mutomimager": 95,
    "polymers": 115,
    "semiconductors": 21,
    "steel": 945,
    "structuralregulators": 81,
    "superconductors": 21,
    "surfacestabilisers": 81,
    "survivalequipment": 14
  },
  "Communication Installation": {
    "aluminium": 1322,
    "ceramiccomposites": 85,
    "computercomponents": 22,
    "copper": 85,
    "foodcartridges": 26,
    "fruitandvegetables": 9,
    "insulatingmembrane": 106,
    "liquidoxygen": 678,
    "microcontrollers": 13,
    "polymers": 170,
    "powergenerators": 9,
    "semiconductors": 34,
    "steel": 2542,
    "superconductors": 60,
    "titanium": 1525,
    "water": 22,
    "waterpurifiers": 13
  },
  "Exploration Hub": {
    "aluminium": 2483,
    "buildingfabricators": 89,
    "ceramiccomposites": 134,
    "computercomponents": 49,
    "copper": 178,
    "emergencypowercells": 45,
    "evacuationshelter": 36,
    "foodcartridges": 54,
    "fruitandvegetables": 36,
    "geologicalequipment": 621,
    "hazardousenvironmentsuits": 249,
    "polymers": 666,
    "powergenerators": 32,
    "steel": 3547,
    "structuralregulators": 267,
    "surfacestabilisers": 1419,
    "survivalequipment": 18
  },
  "Extraction Hub": {
    "aluminium": 2352,
    "bioreducinglichen": 714,
    "buildingfabricators": 210,
    "ceramiccomposites": 252,
    "computercomponents": 38,
    "copper": 84,
    "emergencypowercells": 42,
    "evacuationshelter": 51,
    "foodcartridges": 51,
    "fruitandvegetables": 34,
    "geologicalequipment": 210,
    "hazardousenvironmentsuits": 126,
    "mutomimager": 160,
    "polymers": 672,
    "powergenerators": 26,
    "robotics": 252,
    "steel": 3359,
    "structuralregulators": 504,
    "surfacestabilisers": 756,
    "survivalequipment": 26
  },
  "Government Installation": {
    "aluminium": 1959,
    "ceramiccomposites": 154,
    "computercomponents": 13,
    "copper": 93,
    "foodcartridges": 93,
    "fruitandvegetables": 37,
    "insulatingmembrane": 247,
    "liquidoxygen": 1479,
    "nonlethalweapons": 13,
    "polymers": 370,
    "powergenerators": 13,
    "steel": 3080,
    "titanium": 2341,
    "water": 154,
    "waterpurifiers": 31
  },
  "High Tech Hub": {
    "aluminium": 2512,
    "buildingfabricators": 135,
    "ceramiccomposites": 225,
    "cmmcomposite": 270,
    "computercomponents": 68,
    "copper": 113,
    "emergencypowercells": 59,
    "evacuationshelter": 45,
    "foodcartridges": 54,
    "fruitandvegetables": 36,
    "microcontrollers": 90,
    "polymers": 673,
    "powergenerators": 27,
    "robotics": 449,
    "semiconductors": 108,
    "steel": 3768,
    "structuralregulators": 404,
    "superconductors": 108,
    "surfacestabilisers": 539,
    "survivalequipment": 27,
    "thermalcoolingunits": 211
  },
  "Industrial Hub": {
    "aluminium": 2407,
    "buildingfabricators": 208,
    "ceramiccomposites": 249,
    "cmmcomposite": 166,
    "computercomponents": 38,
    "copper": 83,
    "emergencypowercells": 42,
    "evacuationshelter": 50,
    "foodcartridges": 50,
    "fruitandvegetables": 34,
    "hazardousenvironmentsuits": 83,
    "heliostaticfurnaces": 415,
    "microcontrollers": 50,
    "mineralextractors": 415,
    "polymers": 664,
    "powergenerators": 25,
    "robotics": 332,
    "semiconductors": 75,
    "steel": 3320,
    "structuralregulators": 498,
    "superconductors": 75,
    "surfacestabilisers": 498,
    "survivalequipment": 25,
    "thermalcoolingunits": 117
  },
  "Industrial Settlement: Large": {
    "advancedcatalysers": 123,
    "aluminium": 1755,
    "buildingfabricators": 165,
    "ceramiccomposites": 165,
    "computercomponents": 84,
    "copper": 84,
    "emergencypowercells": 84,
    "evacuationshelter": 63,
    "foodcartridges": 123,
    "fruitandvegetables": 84,
    "hazardousenvironmentsuits": 42,
    "heliostaticfurnaces": 246,
    "liquidoxygen": 816,
    "microcontrollers": 42,
    "mineralextractors": 492,
    "polymers": 327,
    "resonatingseparators": 42,
    "robotics": 165,
    "semiconductors": 42,
    "steel": 3057,
    "structuralregulators": 204,
    "superconductors": 42,
    "surfacestabilisers": 204,
    "survivalequipment": 42,
    "thermalcoolingunits": 42
  },
  "Industrial Settlement: Medium": {
    "advancedcatalysers": 82,
    "aluminium": 1170,
    "buildingfabricators": 110,
    "ceramiccomposites": 110,
    "computercomponents": 56,
    "copper": 56,
    "emergencypowercells": 56,
    "evacuationshelter": 42,
    "foodcartridges": 82,
    "fruitandvegetables": 56,
    "hazardousenvironmentsuits": 28,
    "heliostaticfurnaces": 164,
    "liquidoxygen": 544,
    "microcontrollers": 28,
    "mineralextractors": 328,
    "polymers": 218,
    "resonatingseparators": 28,
    "robotics": 110,
    "semiconductors": 28,
    "steel": 2038,
    "structuralregulators": 136,
    "superconductors": 28,
    "surfacestabilisers": 136,
    "survivalequipment": 28,
    "thermalcoolingunits": 28
  },
  "Industrial Settlement: Small": {
    "advancedcatalysers": 41,
    "aluminium": 585,
    "buildingfabricators": 55,
    "ceramiccomposites": 55,
    "computercomponents": 28,
    "copper": 28,
    "emergencypowercells": 28,
    "evacuationshelter": 21,
    "foodcartridges": 41,
    "fruitandvegetables": 28,
    "hazardousenvironmentsuits": 14,
    "heliostaticfurnaces": 82,
    "liquidoxygen": 272,
    "microcontrollers": 14,
    "mineralextractors": 164,
    "polymers": 109,
    "resonatingseparators": 14,
    "robotics": 55,
    "semiconductors": 14,
    "steel": 1019,
    "structuralregulators": 68,
    "superconductors": 14,
    "surfacestabilisers": 68,
    "survivalequipment": 14,
    "thermalcoolingunits": 14
  },
  "Large Planetary Port": {
    "aluminium": 42282,
    "buildingfabricators": 2442,
    "ceramiccomposites": 4884,
    "cmmcomposite": 40656,
    "computercomponents": 408,
    "copper": 2442,
    "emergencypowercells": 272,
    "evacuationshelter": 816,
    "foodcartridges": 544,
    "fruitandvegetables": 380,
    "liquidoxygen": 14232,
    "medicaldiagnosticequipment": 192,
    "nonlethalweapons": 136,
    "polymers": 2712,
    "powergenerators": 272,
    "semiconductors": 408,
    "steel": 60984,
    "structuralregulators": 2712,
    "superconductors": 544,
    "surfacestabilisers": 3660,
    "survivalequipment": 220,
    "terrainenrichmentsystems": 272,
    "titanium": 34560
  },
  "Medical Installation": {
    "aluminium": 1357,
    "basicmedicines": 50,
    "ceramiccomposites": 155,
    "combatstabilisers": 19,
    "computercomponents": 31,
    "copper": 112,
    "foodcartridges": 75,
    "fruitandvegetables": 50,
    "hazardousenvironmentsuits": 25,
    "insulatingmembrane": 309,
    "liquidoxygen": 1727,
    "medicaldiagnosticequipment": 99,
    "polymers": 371,
    "powergenerators": 19,
    "steel": 3084,
    "titanium": 2282,
    "water": 278,
    "waterpurifiers": 38
  },
  "Military Hub": {
    "aluminium": 2414,
    "basicmedicines": 109,
    "battleweapons": 42,
    "buildingfabricators": 333,
    "ceramiccomposites": 375,
    "cmmcomposite": 333,
    "combatstabilisers": 25,
    "computercomponents": 75,
    "copper": 105,
    "emergencypowercells": 63,
    "evacuationshelter": 75,
    "foodcartridges": 125,
    "fruitandvegetables": 42,
    "microcontrollers": 55,
    "militarygradefabrics": 42,
    "polymers": 708,
    "powergenerators": 38,
    "reactivearmour": 42,
    "steel": 3746,
    "structuralregulators": 542,
    "surfacestabilisers": 583,
    "survivalequipment": 50
  },
  "Civilian Hub": {
    "agriculturalmedicines": 235,
    "aluminium": 2433,
    "biowaste": 630,
    "buildingfabricators": 84,
    "ceramiccomposites": 126,
    "computercomponents": 21,
    "copper": 68,
    "cropharvesters": 210,
    "emergencypowercells": 42,
    "evacuationshelter": 68,
    "foodcartridges": 68,
    "fruitandvegetables": 42,
    "pesticides": 378,
    "polymers": 630,
    "powergenerators": 26,
    "steel": 3775,
    "structuralregulators": 336,
    "surfacestabilisers": 588,
    "survivalequipment": 38,
    "terrainenrichmentsystems": 126
  },
  "Military Installation": {
    "aluminium": 1317,
    "basicmedicines": 24,
    "battleweapons": 30,
    "ceramiccomposites": 238,
    "cmmcomposite": 356,
    "combatstabilisers": 48,
    "computercomponents": 42,
    "copper": 131,
    "foodcartridges": 107,
    "fruitandvegetables": 48,
    "insulatingmembrane": 178,
    "liquidoxygen": 1424,
    "microcontrollers": 18,
    "militarygradefabrics": 36,
    "polymers": 416,
    "powergenerators": 18,
    "reactivearmour": 30,
    "steel": 2966,
    "titanium": 2373,
    "water": 238,
    "waterpurifiers": 42
  },
  "Military Settlement: Large": {
    "aluminium": 1779,
    "basicmedicines": 108,
    "battleweapons": 72,
    "buildingfabricators": 180,
    "ceramiccomposites": 180,
    "cmmcomposite": 1068,
    "combatstabilisers": 108,
    "computercomponents": 126,
    "copper": 90,
    "emergencypowercells": 72,
    "evacuationshelter": 108,
    "foodcartridges": 108,
    "fruitandvegetables": 72,
    "liquidoxygen": 516,
    "microcontrollers": 36,
    "militarygradefabrics": 72,
    "polymers": 357,
    "reactivearmour": 72,
    "steel": 2847,
    "structuralregulators": 303,
    "surfacestabilisers": 180,
    "survivalequipment": 72
  },
  "Military Settlement: Medium": {
    "aluminium": 1186,
    "basicmedicines": 72,
    "battleweapons": 48,
    "buildingfabricators": 120,
    "ceramiccomposites": 120,
    "cmmcomposite": 712,
    "combatstabilisers": 72,
    "computercomponents": 84,
    "copper": 60,
    "emergencypowercells": 48,
    "evacuationshelter": 72,
    "foodcartridges": 72,
    "fruitandvegetables": 48,
    "liquidoxygen": 344,
    "microcontrollers": 24,
    "militarygradefabrics": 48,
    "polymers": 238,
    "reactivearmour": 48,
    "steel": 1898,
    "structuralregulators": 202,
    "surfacestabilisers": 120,
    "survivalequipment": 48
  },
  "Military Settlement: Small": {
    "aluminium": 593,
    "basicmedicines": 36,
    "battleweapons": 24,
    "buildingfabricators": 60,
    "ceramiccomposites": 60,
    "cmmcomposite": 356,
    "combatstabilisers": 36,
    "computercomponents": 42,
    "copper": 30,
    "emergencypowercells": 24,
    "evacuationshelter": 36,
    "foodcartridges": 36,
    "fruitandvegetables": 24,
    "liquidoxygen": 172,
    "microcontrollers": 12,
    "militarygradefabrics": 24,
    "polymers": 119,
    "reactivearmour": 24,
    "steel": 949,
    "structuralregulators": 101,
    "surfacestabilisers": 60,
    "survivalequipment": 24
  },
  "Mining Settlement: Large": {
    "aluminium": 1896,
    "bioreducinglichen": 486,
    "buildingfabricators": 177,
    "ceramiccomposites": 177,
    "computercomponents": 90,
    "copper": 90,
    "emergencypowercells": 288,
    "evacuationshelter": 90,
    "foodcartridges": 135,
    "fruitandvegetables": 90,
    "geologicalequipment": 156,
    "hazardousenvironmentsuits": 45,
    "liquidoxygen": 531,
    "mutomimager": 135,
    "polymers": 354,
    "robotics": 177,
    "steel": 3084,
    "structuralregulators": 222,
    "surfacestabilisers": 267,
    "survivalequipment": 45
  },
  "Mining Settlement: Medium": {
    "aluminium": 1264,
    "bioreducinglichen": 324,
    "buildingfabricators": 118,
    "ceramiccomposites": 118,
    "computercomponents": 60,
    "copper": 60,
    "emergencypowercells": 192,
    "evacuationshelter": 60,
    "foodcartridges": 90,
    "fruitandvegetables": 60,
    "geologicalequipment": 104,
    "hazardousenvironmentsuits": 30,
    "liquidoxygen": 354,
    "mutomimager": 90,
    "polymers": 236,
    "robotics": 118,
    "steel": 2056,
    "structuralregulators": 148,
    "surfacestabilisers": 178,
    "survivalequipment": 30
  },
  "Mining Settlement: Small": {
    "aluminium": 632,
    "bioreducinglichen": 162,
    "buildingfabricators": 59,
    "ceramiccomposites": 59,
    "computercomponents": 30,
    "copper": 30,
    "emergencypowercells": 96,
    "evacuationshelter": 30,
    "foodcartridges": 45,
    "fruitandvegetables": 30,
    "geologicalequipment": 52,
    "hazardousenvironmentsuits": 15,
    "liquidoxygen": 177,
    "mutomimager": 45,
    "polymers": 118,
    "robotics": 59,
    "steel": 1028,
    "structuralregulators": 74,
    "surfacestabilisers": 89,
    "survivalequipment": 15
  },
  "Mining/Industrial Installation": {
    "aluminium": 921,
    "bioreducinglichen": 172,
    "ceramiccomposites": 86,
    "computercomponents": 13,
    "copper": 52,
    "foodcartridges": 52,
    "fruitandvegetables": 18,
    "geologicalequipment": 26,
    "hazardousenvironmentsuits": 13,
    "insulatingmembrane": 129,
    "liquidoxygen": 1028,
    "mutomimager": 43,
    "polymers": 215,
    "powergenerators": 9,
    "resonatingseparators": 22,
    "robotics": 60,
    "steel": 2141,
    "titanium": 1628,
    "water": 73,
    "waterpurifiers": 22
  },
  "Outpost Hub": {
    "aluminium": 2797,
    "buildingfabricators": 290,
    "ceramiccomposites": 145,
    "computercomponents": 25,
    "copper": 78,
    "emergencypowercells": 49,
    "evacuationshelter": 49,
    "foodcartridges": 174,
    "fruitandvegetables": 87,
    "polymers": 724,
    "powergenerators": 25,
    "steel": 4051,
    "structuralregulators": 338,
    "surfacestabilisers": 1061,
    "survivalequipment": 29
  },
  "Pirate Base Installation": {
    "aluminium": 1233,
    "battleweapons": 23,
    "beer": 380,
    "ceramiccomposites": 95,
    "computercomponents": 19,
    "copper": 57,
    "foodcartridges": 61,
    "fruitandvegetables": 16,
    "insulatingmembrane": 95,
    "liquidoxygen": 911,
    "liquor": 228,
    "polymers": 190,
    "powergenerators": 8,
    "reactivearmour": 23,
    "steel": 1707,
    "titanium": 1594,
    "water": 65,
    "waterpurifiers": 16
  },
  "Refinery Hub": {
    "advancedcatalysers": 112,
    "aluminium": 2697,
    "buildingfabricators": 233,
    "ceramiccomposites": 279,
    "computercomponents": 42,
    "copper": 93,
    "emergencypowercells": 47,
    "evacuationshelter": 56,
    "foodcartridges": 56,
    "fruitandvegetables": 38,
    "hazardousenvironmentsuits": 117,
    "polymers": 744,
    "powergenerators": 28,
    "resonatingseparators": 84,
    "robotics": 419,
    "steel": 3720,
    "structuralregulators": 465,
    "surfacestabilisers": 558,
    "survivalequipment": 28,
    "thermalcoolingunits": 103
  },
  "Relay Installation": {
    "aluminium": 1033,
    "ceramiccomposites": 98,
    "computercomponents": 25,
    "copper": 88,
    "foodcartridges": 30,
    "fruitandvegetables": 10,
    "insulatingmembrane": 122,
    "liquidoxygen": 780,
    "polymers": 195,
    "powergenerators": 10,
    "semiconductors": 39,
    "steel": 2437,
    "superconductors": 59,
    "titanium": 1755,
    "water": 25,
    "waterpurifiers": 15
  },
  "Research Installation": {
    "advancedcatalysers": 44,
    "aluminium": 1380,
    "basicmedicines": 13,
    "ceramiccomposites": 157,
    "computercomponents": 38,
    "copper": 126,
    "foodcartridges": 76,
    "fruitandvegetables": 26,
    "geologicalequipment": 26,
    "hazardousenvironmentsuits": 32,
    "insulatingmembrane": 314,
    "liquidoxygen": 1506,
    "medicaldiagnosticequipment": 51,
    "microcontrollers": 13,
    "mutomimager": 38,
    "polymers": 377,
    "powergenerators": 13,
    "semiconductors": 51,
    "steel": 3136,
    "superconductors": 88,
    "titanium": 2383,
    "water": 157,
    "waterpurifiers": 38
  },
  "Satellite Installation": {
    "aluminium": 1322,
    "ceramiccomposites": 85,
    "computercomponents": 22,
    "copper": 85,
    "foodcartridges": 26,
    "fruitandvegetables": 9,
    "insulatingmembrane": 106,
    "liquidoxygen": 678,
    "microcontrollers": 13,
    "polymers": 170,
    "powergenerators": 9,
    "semiconductors": 34,
    "steel": 2542,
    "superconductors": 60,
    "titanium": 1525,
    "water": 22,
    "waterpurifiers": 13
  },
  "Scientific Hub": {
    "advancedcatalysers": 170,
    "aluminium": 2581,
    "basicmedicines": 72,
    "buildingfabricators": 178,
    "ceramiccomposites": 223,
    "computercomponents": 67,
    "copper": 112,
    "emergencypowercells": 63,
    "evacuationshelter": 36,
    "foodcartridges": 54,
    "fruitandvegetables": 36,
    "geologicalequipment": 401,
    "hazardousenvironmentsuits": 156,
    "medicaldiagnosticequipment": 161,
    "microcontrollers": 49,
    "mutomimager": 107,
    "polymers": 712,
    "powergenerators": 36,
    "semiconductors": 72,
    "steel": 3560,
    "structuralregulators": 445,
    "superconductors": 72,
    "surfacestabilisers": 534,
    "survivalequipment": 27
  },
  "Security Installation": {
    "aluminium": 1774,
    "battleweapons": 19,
    "ceramiccomposites": 122,
    "combatstabilisers": 25,
    "computercomponents": 31,
    "copper": 122,
    "foodcartridges": 37,
    "fruitandvegetables": 13,
    "insulatingmembrane": 183,
    "liquidoxygen": 1458,
    "militarygradefabrics": 19,
    "nonlethalweapons": 19,
    "polymers": 243,
    "powergenerators": 13,
    "steel": 3645,
    "titanium": 2309,
    "water": 31,
    "waterpurifiers": 19
  },
  "Space Bar Installation": {
    "aluminium": 1217,
    "animalmeat": 38,
    "beer": 497,
    "ceramiccomposites": 125,
    "coffee": 63,
    "computercomponents": 13,
    "copper": 75,
    "fish": 19,
    "fruitandvegetables": 38,
    "insulatingmembrane": 249,
    "liquidoxygen": 1738,
    "liquor": 311,
    "polymers": 311,
    "powergenerators": 13,
    "steel": 2483,
    "tea": 187,
    "titanium": 1738,
    "water": 311,
    "waterpurifiers": 38,
    "wine": 621
  },
  "Space Farm": {
    "agriculturalmedicines": 115,
    "aluminium": 842,
    "biowaste": 153,
    "ceramiccomposites": 77,
    "computercomponents": 12,
    "copper": 46,
    "cropharvesters": 77,
    "foodcartridges": 46,
    "fruitandvegetables": 69,
    "grain": 92,
    "insulatingmembrane": 192,
    "liquidoxygen": 1071,
    "pesticides": 123,
    "polymers": 230,
    "powergenerators": 8,
    "steel": 1912,
    "titanium": 1453,
    "water": 173,
    "waterpurifiers": 31
  },
  "Tourist Installation": {
    "aluminium": 1269,
    "animalmeat": 78,
    "beer": 389,
    "ceramiccomposites": 130,
    "coffee": 130,
    "computercomponents": 13,
    "copper": 78,
    "fish": 39,
    "fruitandvegetables": 65,
    "insulatingmembrane": 259,
    "liquidoxygen": 1813,
    "liquor": 195,
    "polymers": 324,
    "powergenerators": 13,
    "steel": 2589,
    "tea": 259,
    "titanium": 1813,
    "water": 324,
    "waterpurifiers": 39,
    "wine": 259
  },
  "Tourist Settlement: Large": {
    "aluminium": 1527,
    "animalmeat": 213,
    "beer": 933,
    "buildingfabricators": 87,
    "ceramiccomposites": 129,
    "coffee": 213,
    "computercomponents": 45,
    "copper": 66,
    "emergencypowercells": 45,
    "evacuationshelter": 66,
    "fish": 108,
    "fruitandvegetables": 213,
    "liquidoxygen": 681,
    "liquor": 384,
    "polymers": 342,
    "steel": 2121,
    "structuralregulators": 171,
    "surfacestabilisers": 171,
    "survivalequipment": 45,
    "tea": 510,
    "wine": 468
  },
  "Tourist Settlement: Medium": {
    "aluminium": 1018,
    "animalmeat": 142,
    "beer": 622,
    "buildingfabricators": 58,
    "ceramiccomposites": 86,
    "coffee": 142,
    "computercomponents": 30,
    "copper": 44,
    "emergencypowercells": 30,
    "evacuationshelter": 44,
    "fish": 72,
    "fruitandvegetables": 142,
    "liquidoxygen": 454,
    "liquor": 256,
    "polymers": 228,
    "steel": 1414,
    "structuralregulators": 114,
    "surfacestabilisers": 114,
    "survivalequipment": 30,
    "tea": 340,
    "wine": 312
  },
  "Tourist Settlement: Small": {
    "aluminium": 509,
    "animalmeat": 71,
    "beer": 311,
    "buildingfabricators": 29,
    "ceramiccomposites": 43,
    "coffee": 71,
    "computercomponents": 15,
    "copper": 22,
    "emergencypowercells": 15,
    "evacuationshelter": 22,
    "fish": 36,
    "fruitandvegetables": 71,
    "liquidoxygen": 227,
    "liquor": 128,
    "polymers": 114,
    "steel": 707,
    "structuralregulators": 57,
    "surfacestabilisers": 57,
    "survivalequipment": 15,
    "tea": 170,
    "wine": 156
  }
};